# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
  - repo: http://github.com/ambv/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: http://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        entry: bin/pre-commit-wrapper.py mypy
        additional_dependencies: ["pip==22.0.*"]
  - repo: http://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: http://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
