---
- name: Playbook to test sourcing env variables from private config and loaded vars
  hosts: "{{ target | default('localhost') }}"

  pre_tasks:
    - name: Source all env varsiables
      ansible.builtin.include_tasks:
        file: "../tasks/load-envs.yml"

  tasks:
    - name: Debug loaded vars
      ansible.builtin.debug:
        var: vars

    - name: Debug Elasticsearch directories
      ansible.builtin.debug:
        msg:
          - "Templates directory: {{ elasticsearch_templates_dir | default('Not defined') }}"
          - "Files directory: {{ elasticsearch_files_dir | default('Not defined') }}"

    - name: Display test private environment variables
      ansible.builtin.debug:
        msg: "SENTRY_ENVIRONMENT: {{ sourced_env.SENTRY_ENVIRONMENT }}, SENTRY_DSN: {{ sourced_env.SENTRY_DSN }}"

    - name: Display es_config
      ansible.builtin.debug:
        msg: "{{ es_config }}"

    - name: Display inventory_hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

    - name: Display mc_es_seed_hosts
      ansible.builtin.debug:
        msg: "{{ mc_es_seed_hosts }}"

    - name: Display mc_es_master
      ansible.builtin.debug:
        msg: "{{ mc_es_master }}"
