---
docker_elasticsearch_nodes:
  - name: es-node-01
    mc_es_http_port: 9229
    mc_es_transport_port: 9329
  - name: es-node-02
    mc_es_http_port: 9230
    mc_es_transport_port: 9330
  - name: es-node-03
    mc_es_http_port: 9231
    mc_es_transport_port: 9331

# Elasticsearch Configuration as per Ansible role
es_data_dirs: ["/usr/share/elasticsearch/data"]
es_heap_size: "1g"
es_log_dir: "/var/log/elasticsearch"
es_templates: false
es_templates_fileglob: ""
es_version: "8.17.3"

# Use different variable name instead of modifying Ansible default hash_behavior on merging dictionaries
# https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-hash-behaviour
local_es_config:
  network.publish_host: "_eth0_"

mc_es_seed_hosts:
  - "es-node-01"
  - "es-node-02"
  - "es-node-03"
